name: deploy
on:
  push:
    branches: [master]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy build to the server
        uses: appleboy/scp-action@master
        with:
          host: 82.148.16.21
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          source: "build,public,node_modules"
          target: "/home/deployer/snappy-worker"
          rm: true
      - name: "Run app"
        uses: appleboy/ssh-action@master
        with:
          host: 82.148.16.21
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd snappy-worker
            touch .env
            echo "PORT=8080" >> .env
            echo "CONFIRMATION=7f700990" >> .env
            echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
            pm2 restart snappy-worker
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Change directory
        run: cd frontend
      - name: Install
        run: npm ci
      - name: Build
        run: npm run build
      - name: Copy build to the server
        uses: appleboy/scp-action@master
        with:
          host: 82.148.16.21
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          source: "build"
          target: "/home/deployer/snappy-worker/public"
          rm: true
